name: Python-Env

on:
  push:
    branches:
      - "dep-package"

jobs:
  python_env_win:
    permissions:
      contents: "write"
      packages: "write"
      pull-requests: "read"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          path: mox
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: comfyanonymous/ComfyUI
          path: ComfyUI
      - shell: bash
        run: |
          cd ..
          ls

          curl https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip -o python_embeded.zip
          unzip python_embeded.zip -d python_env_win
          cd python_env_win
          echo 'import site' >> ./python310._pth
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          ./python.exe get-pip.py
          ./python.exe -s -m pip install --upgrade torch torchvision torchaudio xformers
          ./python.exe -s -m pip install -r ../mox/ComfyUI/requirements.txt
          ./python.exe -s -m pip install -r ../mox/mox/agent/requirements.txt
          cd ..
          ls

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r python_env_win.zip python_env_win

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          file: python_env_win.zip
          tag: "latest"
          overwrite: true
