name: Python-Env

on:
  push:
    branches:
      - "dep-package"

env:
  python_env_win_version: "v0.0.1"
  comfyui_commit: "b8218522f112be2e69fd49bbefbe68b57868baa0"

jobs:
  python_env_win:
    permissions:
      contents: "write"
      packages: "write"
      pull-requests: "read"
    runs-on: windows-latest
    steps:
      - name: "checkout mox"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          path: mox
      - name: "checkout ComfyUI"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: comfyanonymous/ComfyUI
          path: ComfyUI
          ref: ${{ env.comfyui_commit }}
      - name: "package python_env_win"
        shell: bash
        run: |
          cd ..
          ls

          curl https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip -o python_embeded.zip
          unzip python_embeded.zip -d python_env_win
          cd python_env_win
          echo 'import site' >> ./python310._pth
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          ./python.exe get-pip.py
          ./python.exe -s -m pip install --upgrade torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2
          ./python.exe -s -m pip install --upgrade xformers==0.0.25.post1
          ./python.exe -s -m pip install -r ../mox/ComfyUI/requirements.txt
          ./python.exe -s -m pip install -r ../mox/mox/agent/requirements.txt
          cd ..

          "C:\Program Files\7-Zip\7z.exe" a -tzip mox/python_env_win_${{ env.python_env_win_version }}.zip python_env_win/*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          file: python_env_win_${{ env.python_env_win_version }}.zip
          tag: "latest"
          overwrite: true

      - name: "prepare python 3.10"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - name: "upload model to modelscope"
        shell: bash
        run: |
          pwd
          ls
          pip install modelscope

          # ha ha ha ..
          mv mox/tools/modelscope .
          mv python_env_win_${{ env.python_env_win_version }}.zip modelscope/model-template/
          cd modelscope
          python upload_model.py
        env:
          MODELSCOPE_ACCESS_TOKEN: ${{ secrets.MODELSCOPE_ACCESS_TOKEN }}
          MODELSCOPE_MODEL_ID: moxying/base-win-model-${{ env.python_env_win_version }}
          MODELSCOPE_MODEL_DIR: model-template
