name: Sync-Code

on:
  push:
    branches:
      - main

jobs:
  push-to-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git init
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git fetch --all
          for branch in `git branch -a | grep remotes | grep -v HEAD`; do
            git branch --track ${branch##*/} $branch
          done
        env:
          GITHUB_REPOSITORY: moxying/mox

      - name: Push to gitcode
        run: |
          remote_repo="https://oauth2:${GITCODE_ACCESS_TOKEN}@gitcode.com/${GITCODE_REPOSITORY}.git"

          git remote add gitcode "${remote_repo}"
          git show-ref # useful for debugging
          git branch --verbose

          # publish all
          git push --all --force gitcode
          git push --tags --force gitcode
        env:
          GITCODE_REPOSITORY: moxying/mox
          GITCODE_ACCESS_TOKEN: ${{ secrets.GITCODE_ACCESS_TOKEN}}
